server:
  port: 8000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri: http://localhost:8060
              predicates:
                - Path=/api/v1.0/product/**
            - id: order-service
              uri: http://localhost:8061
              predicates:
                - Path=/api/v1.0/order/**
