server:
  port: 8000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri: http://localhost:8060
              predicates:
                - Path=/api/v1.0/product/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: productServiceCircuitBreaker
                    fallbackUri: forward:/fallback/product

            - id: order-service
              uri: http://localhost:8061
              predicates:
                - Path=/api/v1.0/order/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: OrderServiceCircuitBreaker
                    fallbackUri: forward:/fallback/order

            - id: inventory-service
              uri: http://localhost:8062
              predicates:
                - Path=/api/v1.0/inventory/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: InventoryServiceCircuitBreaker
                    fallbackUri: forward:/fallback/inventory

#           swagger route for product-service
            - id: product-swagger-docs
              uri: http://localhost:8060
              predicates:
                - Path=/aggregate/product-service/**
              filters:
                - RewritePath=/aggregate/product-service/(?<segment>.*), /$\{segment}

#           swagger route for order-service
            - id: order-swagger-docs
              uri: http://localhost:8061
              predicates:
                - Path=/aggregate/order-service/**
              filters:
                - RewritePath=/aggregate/order-service/(?<segment>.*), /$\{segment}

#           swagger route for inventory-service
            - id: inventory-swagger-docs
              uri: http://localhost:8062
              predicates:
                - Path=/aggregate/inventory-service/**
              filters:
                - RewritePath=/aggregate/inventory-service/(?<segment>.*), /$\{segment}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9092/realms/ecommerce-microservices-security-realm

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Product-Service
        url: /aggregate/product-service/api-docs
      - name: Order-Service
        url: /aggregate/order-service/api-docs
      - name: Inventory-Service
        url: /aggregate/inventory-service/api-docs

  api-docs:
    path: /api-docs

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10
    instances:
      productServiceCircuitBreaker:
        baseConfig: default
      OrderServiceCircuitBreaker:
        baseConfig: default
      InventoryServiceCircuitBreaker:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 6s
        cancelRunningFuture: true
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 5s
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
        ignoreExceptions:
          - java.lang.IllegalArgumentException

management:
  endpoint:
    web:
      exposure:
        include: health, info , metrics, prometheus, circuitbreakers
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true


