server:
  port: 8061

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3307/order_service
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

  inventory:
    client:
      url: http://localhost:8062

springdoc:
  swagger-ui:
    path: /swagger-ui.html
#http://localhost:8061/swagger-ui.html

  api-docs:
    path: /api-docs
#  http://localhost:8061/api-docs