server:
  port: 8062

spring:
  application:
    name: inventory-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/inventory_service
    username: ${USERNAME}
    password: ${ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  #http://localhost:8062/swagger-ui.html

  api-docs:
    path: /api-docs
#  http://localhost:8062/api-docs