services:
  keycloak-db:
    image: postgres:15
    container_name: postgres-keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak-ecommerce-micro
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: pass
    command: ["start-dev", "--import-realm"]
    ports:
      - "9092:8080"
    depends_on:
      - keycloak-db
    networks:
      - keycloak-network

volumes:
  keycloak-db-data:

networks:
  keycloak-network:





